### ISSUE TITLE
You didn't solve the captcha yet. Need to refresh to avoid endless loop.

### ISSUE THREAD

**Issue by nanchaara** [1tzkaos/tiktokv4#6]
![image](https://user-images.githubusercontent.com/71387731/116159733-f36e1c00-a71a-11eb-84ce-b95776efeaee.png)

**Comment by thanhtuvietnam** [comment]
just keep going and u get the result bro

**Comment by ezzcodeezzlife** [comment]
+1 same problem. does not resolve itself

**Comment by nanchaara** [comment]
> +1 same problem. does not resolve itself

i think you just need to wait, because the website need 1-2 minutes cooldown to get another views
